Try a maybe-better coverage bot

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -74,6 +74,7 @@ jobs:
           name: jest-reports
           path: test/html_reports/*
   minitest:
+    permissions: write-all
     name: minitest
     runs-on: ubuntu-latest
     env:
@@ -109,10 +110,23 @@ jobs:
         run: bundle exec rails db:create db:migrate
       - name: Run tests
         run: TERM=xterm-color bundle exec rails test
-      - name: Code Coverage Summary Report
-        uses: irongut/CodeCoverageSummary@v1.3.0
+      - name: Generate Coverage Report
+        uses: clearlyip/code-coverage-report-action@v4
+        id: code_coverage_report_action
+        #Dont run for dependabot unless you fix PR comment permissions
+        if: ${{ github.actor != 'dependabot[bot]'}}
         with:
-          filename: coverage/coverage.xml
+          #Location of the generate coverage file
+          filename: 'coverage/coverage.xml'
+          fail_on_negative_difference: true
+          artifact_download_workflow_names: 'ci,cron'
+      - name: Add Coverage PR Comment
+        uses: marocchino/sticky-pull-request-comment@v2
+        #Make sure the report was generated and that the event is actually a pull request, run if failed or success
+        if: steps.code_coverage_report_action.outputs.file != '' && github.event_name == 'pull_request' && (success() || failure())
+        with:
+          recreate: true
+          path: code-coverage-results.md
       - name: Publish Test Report
         uses: mikepenz/action-junit-report@v4
         if: always() # always run even if the previous step fails
